drop schema if exists public cascade;
create schema public;

grant usage on schema public to postgres, anon, authenticated, service_role;
grant all on schema public to postgres, service_role;

create extension if not exists pgcrypto with schema public;

create type public.role as enum ('student', 'admin', 'owner');
create type public.section_type as enum ('solo', 'group');

create table public.profile (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role public.role not null default 'student',
  email text,
  phone text,
  profile_picture_url text,
  preference text default 'no_preference',
  bio text,
  study_mode text not null default 'group',

  constraint profile_phone_digits_check check (phone is null or phone ~ '^[0-9]{10}$'),
  constraint profile_preference_check check (preference is null or preference in ('in_person', 'online', 'no_preference')),
  constraint profile_bio_length_check check (bio is null or char_length(bio) <= 500),
  constraint profile_study_mode_check check (study_mode in ('group', 'independent'))
);

create table public.agenda (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  week integer not null unique,
  start_date date not null,
  end_date date not null,
  enabled boolean not null default true
);

create table public.section (
  id bigint generated by default as identity primary key,
  agenda_id bigint not null references public.agenda(id) on delete cascade,
  title text not null,
  description text,
  type public.section_type not null,
  "order" integer,
  unique (agenda_id, "order")
);

create table public.task (
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.section(id) on delete cascade,
  title text not null,
  description text,
  link text,
  "order" integer,
  unique (section_id, "order")
);

-- ============================================================
-- time_slot table
-- Static lookup table - every 1hr block from 7am-11pm, Mon-Sun
-- 16 slots/day x 7 days = 112 rows total
-- Seeded once on setup, never written to by the app
-- ============================================================

create table if not exists public.time_slot (
  id          serial primary key,
  day         int not null check (day between 0 and 6),   -- 0=Mon, 6=Sun
  start_time  time not null,
  end_time    time not null,
  slot_index  int not null unique                          -- (day * 16) + position in day, used by matching algorithm
);

-- Seed all 112 slots (7am-11pm, 1hr blocks, Mon-Sun)
-- Safe to re-run - skips if table already has data
do $$
declare
  d int;
  s int;
  start_t time;
  end_t   time;
  base    time := '07:00:00';  -- grid starts at 7am
begin
  if (select count(*) from public.time_slot) = 0 then
    for d in 0..6 loop
      for s in 0..15 loop  -- 16 slots per day (7am to 11pm)
        start_t := base + (s * interval '1 hour');
        end_t   := start_t + interval '1 hour';
        insert into public.time_slot (day, start_time, end_time, slot_index)
        values (d, start_t, end_t, (d * 16) + s);
      end loop;
    end loop;
  end if;
end $$;

create table public.availability (
  user_id uuid not null references public.profile(user_id) on delete cascade,
  time_slot_id integer not null references public.time_slot(id) on delete cascade,
  updated_at timestamptz not null default now(),
  primary key (user_id, time_slot_id)
);

create table public.room (
  id bigint generated by default as identity primary key,
  building text not null,
  room_number text not null,
  group_capacity integer
);

create table public.room_day (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.room(id) on delete cascade,
  day integer not null check (day >= 0 and day <= 4),
  unique (room_id, day)
);

create table public."group" (
  id uuid primary key default gen_random_uuid(),
  preference text default 'in_person' check (preference in ('in_person', 'online')),
  day_of_week integer check (day_of_week >= 0 and day_of_week <= 6),
  meet_start_time time not null,
  meet_end_time time not null,
  created_at timestamptz not null default now(),
  room_id bigint references public.room(id) on delete set null,
  room_overbooked boolean not null default false
);

create table public.member_of (
  group_id uuid not null references public."group"(id) on delete cascade,
  user_id uuid not null references public.profile(user_id) on delete cascade,
  primary key (group_id, user_id)
);

create table public.task_completion (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profile(user_id) on delete cascade,
  task_id bigint not null references public.task(id) on delete cascade,
  completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, task_id)
);

create index task_completion_task_id_idx on public.task_completion(task_id);
create index task_completion_user_id_idx on public.task_completion(user_id);

create or replace function public.is_owner()
returns boolean
language sql
security definer
set search_path to 'public'
as $$
  select exists (
    select 1 from public.profile
    where user_id = (select auth.uid())
      and role = 'owner'
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path to 'public'
as $$
  select exists (
    select 1 from public.profile
    where user_id = (select auth.uid())
      and role in ('admin', 'owner')
  );
$$;

create or replace function public.create_profile_for_new_user()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  insert into public.profile (user_id, email, role, preference)
  values (new.id, new.email, 'student', 'no_preference')
  on conflict (user_id) do update
    set email = excluded.email;

  return new;
end;
$$;

create or replace function public.set_availability_updated_at()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.set_task_completion_updated_at()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.prevent_profile_protected_updates()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  -- Only owners can change roles
  if new.role is distinct from old.role
     and not public.is_owner() then
    raise exception 'Only owners may change roles';
  end if;

  -- Nobody can change user IDs
  if new.user_id is distinct from old.user_id then
    raise exception 'Not allowed to update user_id';
  end if;

  -- Nobody manually changes email
  if new.email is distinct from old.email then
    raise exception 'Not allowed to update email';
  end if;

  return new;
end;
$$;

-- Allows owners to promote students to admins or demote admins to students.
create or replace function public.set_user_role(
  target_user uuid,
  new_role public.role
)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  target_role public.role;
begin
  -- Only owners may change roles
  if not public.is_owner() then
    raise exception 'Owner only';
  end if;

  -- Verify target exists and get current role
  select role
  into target_role
  from public.profile
  where user_id = target_user;

  if target_role is null then
    raise exception 'User not found';
  end if;

  -- Prevent owners from demoting themselves
  if target_user = auth.uid() then
    raise exception 'Cannot change your own role';
  end if;

  update public.profile
  set role = new_role
  where user_id = target_user;
end;
$$;

create or replace function public.shares_group_with(target_user uuid)
returns boolean
language sql
security definer
set search_path to 'public'
as $$
  select exists (
    select 1
    from public.member_of m1
    join public.member_of m2 on m1.group_id = m2.group_id
    where m1.user_id = (select auth.uid())
      and m2.user_id = target_user
  );
$$;

create or replace function public.can_view_task_completion(target_user_id uuid)
returns boolean
language sql
security definer
set search_path to 'public'
as $$
  select
    target_user_id = (select auth.uid())
    or public.is_admin()
    or exists (
      select 1
      from public.member_of me
      join public.member_of other on me.group_id = other.group_id
      where me.user_id = (select auth.uid())
        and other.user_id = target_user_id
    );
$$;

create or replace function public.get_my_group_members()
returns table (
  user_id uuid,
  full_name text,
  email text,
  phone text,
  profile_picture_url text,
  bio text
)
language sql
security definer
set search_path to 'public'
as $$
  select p.user_id, p.full_name, p.email, p.phone, p.profile_picture_url, p.bio
  from public.member_of mo
  join public.profile p on p.user_id = mo.user_id
  where mo.group_id in (
    select group_id from public.member_of where user_id = (select auth.uid())
  );
$$;


-- Handles copying of agendas and their sections and tasks
create or replace function public.copy_agenda(source_agenda_id integer)
returns integer
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  new_agenda_id integer;
  source_week integer;
  source_section record;
  new_section_id integer;
begin
  if not public.is_admin() then
    raise exception 'Admin only';
  end if;

  select week
  into source_week
  from public.agenda
  where id = source_agenda_id;

  if source_week is null then
    raise exception 'Cannot copy agenda without a week';
  end if;

  -- Temporarily move rows below the copied agenda
  update public.agenda
  set week = -week
  where week > source_week;

  -- Move them down one
  update public.agenda
  set week = abs(week) + 1
  where week < 0;

  insert into public.agenda (
    title,
    description,
    week,
    start_date,
    end_date,
    enabled
  )
  select
    title || ' Copy',
    description,
    source_week + 1,
    start_date,
    end_date,
    false
  from public.agenda
  where id = source_agenda_id
  returning id into new_agenda_id;

  for source_section in
    select *
    from public.section
    where agenda_id = source_agenda_id
    order by "order"
  loop
    insert into public.section (
      agenda_id,
      title,
      description,
      type,
      "order"
    )
    values (
      new_agenda_id,
      source_section.title,
      source_section.description,
      source_section.type,
      source_section."order"
    )
    returning id into new_section_id;

    insert into public.task (
      section_id,
      title,
      description,
      link,
      "order"
    )
    select
      new_section_id,
      title,
      description,
      link,
      "order"
    from public.task
    where section_id = source_section.id;
  end loop;

  return new_agenda_id;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.create_profile_for_new_user();

create trigger availability_set_updated_at
before update on public.availability
for each row execute function public.set_availability_updated_at();

create trigger task_completion_set_updated_at
before update on public.task_completion
for each row execute function public.set_task_completion_updated_at();

create trigger profile_prevent_protected_updates
before update on public.profile
for each row execute function public.prevent_profile_protected_updates();

alter table public.profile enable row level security;
alter table public.agenda enable row level security;
alter table public.section enable row level security;
alter table public.task enable row level security;
alter table public.task_completion enable row level security;
alter table public.availability enable row level security;
alter table public."group" enable row level security;
alter table public.member_of enable row level security;
alter table public.room enable row level security;
alter table public.room_day enable row level security;
alter table public.time_slot enable row level security;

grant select, insert, update, delete on all tables in schema public to authenticated;
grant select on all tables in schema public to anon;
grant usage, select on all sequences in schema public to authenticated;

create policy "Profile select" on public.profile for select to authenticated using ((user_id = (select auth.uid())) or is_admin());
create policy "Users can insert own profile" on public.profile for insert to authenticated with check (user_id = (select auth.uid()));
create policy "Users can update own profile" on public.profile for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "Admins can delete profiles" on public.profile for delete to authenticated using (is_admin());

create policy "Anyone can view agenda" on public.agenda for select to public using (true);
create policy "Admins can insert agenda" on public.agenda for insert to public with check (is_admin());
create policy "Admins can update agenda" on public.agenda for update to public using (is_admin()) with check (is_admin());
create policy "Admins can delete agenda" on public.agenda for delete to public using (is_admin());

create policy "Anyone can view section" on public.section for select to public using (true);
create policy "Admins can insert section" on public.section for insert to public with check (is_admin());
create policy "Admins can update section" on public.section for update to public using (is_admin()) with check (is_admin());
create policy "Admins can delete section" on public.section for delete to public using (is_admin());

create policy "Anyone can view task" on public.task for select to public using (true);
create policy "Admins can insert task" on public.task for insert to public with check (is_admin());
create policy "Admins can update task" on public.task for update to public using (is_admin()) with check (is_admin());
create policy "Admins can delete task" on public.task for delete to public using (is_admin());

create policy "Users can read relevant task completions" on public.task_completion for select to authenticated using (can_view_task_completion(user_id));
create policy "Users can insert own task completions" on public.task_completion for insert to authenticated with check (user_id = (select auth.uid()));
create policy "Users can update own task completions" on public.task_completion for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "Admins can delete task completions" on public.task_completion for delete to authenticated using (is_admin());

create policy "Users can read own availability" on public.availability for select to authenticated using (auth.uid() = user_id);
create policy "Admins can read all availability" on public.availability for select to authenticated using (is_admin());
create policy "Users can insert own availability" on public.availability for insert to authenticated with check (auth.uid() = user_id);
create policy "Users can delete own availability" on public.availability for delete to authenticated using (auth.uid() = user_id);
create policy "Users can update own availability" on public.availability for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Authenticated users can read time slots" on public.time_slot for select to authenticated using (true);

create policy "Admins can do everything on group" on public."group" for all to public using (is_admin()) with check (is_admin());
create policy "Members can read their own group" on public."group" for select to public using (
  exists (
    select 1 from public.member_of
    where member_of.group_id = "group".id
      and member_of.user_id = auth.uid()
  )
);

create policy "Admins can do everything on member_of" on public.member_of for all to public using (is_admin()) with check (is_admin());
create policy "Students can read their own membership" on public.member_of for select to public using (auth.uid() = user_id);

create policy "room_read_authenticated" on public.room for select to authenticated using (true);
create policy "room_admin_all" on public.room for all to authenticated using (is_admin()) with check (is_admin());

create policy "room_day_read_authenticated" on public.room_day for select to authenticated using (true);
create policy "room_day_admin_all" on public.room_day for all to authenticated using (is_admin()) with check (is_admin());
